// This file declares the IRTDUpdateEvent Interface for Python.
// Generated by makegw.py
// ---------------------------------------------------
//
// Interface Declaration

DEFINE_GUID(IID_IRTDUpdateEvent, 0xa43788c1, 0xd91b, 0x11d3, 0x8f, 0x39, 0x00, 0xc0, 0x4f, 0x36, 0x51, 0xb8);

class PyIRTDUpdateEvent : public PyIDispatch
{
public:
	MAKE_PYCOM_CTOR(PyIRTDUpdateEvent);
	static Excel::IRTDUpdateEvent *GetI(PyObject *self);
	static PyComTypeObject type;

	// The Python methods
	static PyObject *UpdateNotify(PyObject *self, PyObject *args);
	static PyObject *GetHeartbeatInterval(PyObject *self, PyObject *args);
	static PyObject *PutHeartbeatInterval(PyObject *self, PyObject *args);
	static PyObject *Disconnect(PyObject *self, PyObject *args);

protected:
	PyIRTDUpdateEvent(IUnknown *pdisp);
	~PyIRTDUpdateEvent();
};
